### ISSUE TITLE
Consult failing to deal with missing extension [pro].

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#103]
Under ALS Prolog (Threaded) Version 3.3.1-52-g741a19e [darwin].
In ./darwin, make a simple abc.pro, or copy [or softlink] ../../../examples/als/animals.pro.
Then execute
./alspro
…….
Then:
?- consult(animals).
Attempting to consult animals...

Warning: '/Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin/animals.pro' contained syntax errors.
	Unable to remove './darwin/animals.obp'.
Error: Operation attempted on object of type procedure which does not exist.
Operation attempted on: xconsult:topmod(_A).
- Goal:          xconsult:topmod(_A)
- Throw pattern: error(existence_error(procedure,xconsult:topmod(_A)),
                     [xconsult:topmod(_A)])

Expected:  Should attempt to load animals.pro, which would then succeed.

Note that:
?- consult('animals.pro').
Attempting to consult animals.pro...
... consulted /Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin/animals.pro
yes.

**Comment by chuckhoupt** [comment]
I ran git bisect on the problem and it points at e0f2cab71a4a729bb03f32fe424593f4d02c03d8 as the offending commit. Of course, there is a bunch of code controlled by the OBP define...

**Comment by kenbowen** [comment]
I was in the midst of pbi_write-tracking it down when I got distracted by the re-arrival of winter.  Had to figure out how to protect all the plants we had put it over the past week (trying for flowers and milkweed for bees & butterflies).  Now it’s snowing steady wet snow (35 degs), looks like 3-4 inches on the railings already.

Anyway, I tracked it down to a call to obp_open/1 in obp_mode_start/1, which is called in load_source0 (in blt_cslt.pro).
The only other call to obp_open/1 is in builtins.pro, in cslt_blts_ld/3; I think the calls to obp_open[close] here were commented out just before e0f2cab (I believe I commented out too much, which you pointed out).

The source path has been computed to be /Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin/animals.pro, which is fine.

obp_open[close]/1 are C builtins [pbi_obp_open], in loadfile.c.  Haven’t looked at the definition there yet.
Not entirely sure yet what we want.  We said we wanted to suppress creation of obp’s for the builtins, but leave the obp machinery in place for user-defined files.  If so, then I need to figure out why pbi_obp_open failed in this case, and make it succeed.

git bisect sounds interesting.  Without looking, I’m guessing it relates to this:
When I was a grad student in math, there was a common joke about the construction in the Blozanno-Weirstrauss Theorem [That any bounded subset in a euclidean space (e.g, the real line, euclidean plane, etc) has an accumulation point.]  So, here’s how a mathematician hunts lions in Africa. 
1.  Build a north-south fence down the middle of Africa;
2.  Determine which side the the fence the elephant is on;
3.  Build an east-west fence across that side;
4.  Now iterate that construction in 1-3 until the elephant is penned in the remaining space.
5.  Put the gun through the fence ….

Cheers,
—Ken

**Comment by kenbowen** [comment]
So this is one of those cases where I had to bang my head against the wall.  Going a bit further, I added printf’s in bio.c:

int
pbi_obp_open()
{
#ifdef OBP
printf("OBP defined\n");
    PWord v1;
….
#else
printf("OBP NOT defined\n");
    FAIL;
#endif
}

And not too surprisingly, got:

OBP NOT defined

And naturally, from e0f2cab,  in defs.h:

#define OBP   1
#undef OBP

e0f2cab was about supposedly suppressing builtins obp’s, but leaving obp machinery running the user.
In that, it failed.  I think it’s a nice goal, but clearly it’s going to take some more effort.
Maybe a useful question:  How many potential users of the new open ALS Prolog will have machines as weak as those old 386’s etc. that prompted the development of obp’s?  It’s tempting to say that they’ll all be somewhat serious people with serious machines.

Cheers,
——Ken

**Comment by kenbowen** [comment]
We have turned *.obp creation back on (for now), so this issue becomes moot, hence closed.
