### ISSUE TITLE
Update alsprolog.com to use secure HTTPS

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#126]
I believe this involves updating DNS settings and throwing some Github switches:

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by chuckhoupt** [comment]
Yeah, you'll have to update the A records. The https announcement post mentions the issue (meant to link in issue, but forgot):

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

> If you are using A records, you must update your site’s DNS records with new IP addresses. Please see our guide to setting up your custom domain with Pages and update any A records you might have set.

**Comment by kenbowen** [comment]
Ok, got the DH A records changed.  GH now says (checkbox grayed out):

Enforce HTTPS 
— Not yet available for your site because the certificate has not finished being issued.
Please allow 24 hours for this process to complete. (alsprolog.com)

**Comment by kenbowen** [comment]
Done.
