### ISSUE TITLE
Gather All Docs onto master Branch

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#128]
The Problem: Docs are scattered in three different locations.

- gh_pages branch for alsprolog.com
- alshelp on master branch (partial reference manual)
- wiki repo for user manual

For developers, this means that making simple fixes/additions to the docs involves making changes to 2 repos on 2 or 3 different branches -- all the downsides of version control, without functional version control! For users, docs are scattered and not fully available online.

The Solution (on [alldocs branch](/AppliedLogicSystems/ALSProlog/tree/alldocs)):

- [x] Move all docs into the ALSProlog repo on the master branch
- [x] Orginize/compile docs with Github-Pages compatible Jekyll to produce integrated site with all docs
- [x] Reconfigure packaged docs to be build from docs folder

Downsides:

- Increased complexity for generating docs (Jekyll themes and templates)
- Heavier toolset required and a more complex build (Jekyll, etc)

**Comment by kenbowen** [comment]
Yes!
