### ISSUE TITLE
Test on Cygwin unexpectedly stops

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#18]
They stop at "Compare"

**Comment by kenbowen** [comment]
For me, they get all the way thru par2, dying on par3.

**Comment by chuckhoupt** [comment]
Compare fails at test 66.

This minimal query causes alspro to exit: compare(X,f([a]),f([a])).

**Comment by chuckhoupt** [comment]
Cygwin tests no longer fail, because -O optimization has been removed for all compilers.
