### ISSUE TITLE
Command line editing in the ALS Prolog shell 

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#2]
Explore adding a command line editing library to the ALS Prolog shell (blt_shl).  GNU Readline is not suitable because it is licensed under GPL instead of LGPL, which would be incompatible with the MIT license.  Searching for “command line editing libraries” produces definite possibilities:

-- Tecla (http://www.astro.caltech.edu/~mcs/tecla/libtecla-1.6.3.tar.gz) (like UNIX tcsh shell)  Variant of MIT license 
-- antirez/linenoise (https://github.com/antirez/linenoise) Looks compatible with MIT license
-- Editline Library (lib edit) (http://thrysoee.dk/editline/)  BSD-style license

**Comment by chuckhoupt** [comment]
An Mac OS X, libreadline.dylib is actually just a symlink to libedit.dylib, so it isn't a problem.

**Comment by kenbowen** [comment]
[Per Chuck]:
Re: Windows 
Good news: Windows Powershell has built-in editing/history, so no action required. Other Windows command-line environments (Cygwin, Win10-Bash) simulate Unix TTYs, so they can just use the Unix TTY solution.
Perhaps we should point Windows users at Powershell.
