### ISSUE TITLE
ALSDev default font too small

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#20]
The font used for the console/editor is very small compared to the font size used in current OSes.

Note: Ultimately adding font settings (#5) will fix this, but a simple stop-gap measure would be to find a way in Tcl/Tk to set the font size to a system-defined "normal" size (for monospace text)?

**Comment by kenbowen** [comment]
On Jan 23, 2016, at 9:56 AM, Chuck Houpt <notifications@github.com> wrote:

> The font used for the console/editor is very small compared to the font size used in current OSes

Agreed

> 
> Note: Ultimately adding font settings (#5) will fix this, but a simple stop-gap measure would be to find a way in Tcl/Tk to set the font size to a system-defined "normal" size (for monospace text)?

The right way to approach it � probably take one halfway to #5; then just need the UI part.

**Comment by chuckhoupt** [comment]
Well, I'm hoping it is less then halfway to #5. It should be a couple of one-liners. I fooled around with it a few weeks ago (diff below, but I was flailing around). It looks like the constant `TkFixedFont` can be used to select the systems preferred mono-space font. Next we just need to figure out default system sizing. Feel free to assign yourself to this bug, if you want to take a run at it.

![screen shot 2016-01-23 at 1 13 32 pm](https://cloud.githubusercontent.com/assets/1627217/12531845/3688cc7a-c1d3-11e5-8329-d02422f22fb4.png)

**Comment by kenbowen** [comment]
commit a59ce7d41faee7d4a059976763d41604211864ba fixed this.
