### ISSUE TITLE
ALS Prolog web site

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#25]
Set up alsprolog web site as a repo in AppliedLogicSystems.  Decide whether to host it on GitHubPages or on DH.  Decide what should go onto / be said on the site.

Notes from Trello:

Ken:

Yes, GitHub Pages makes sense — was really just acknowledging that it’s currently at DH. At the moment, I can’t imagine sufficient complexity to warrant more than a page: one can always scroll down.

Chuck:

You should definitely give GitHub Pages a try. It should be simple to setup, and it will support push-to-deploy out of the box. If the site needs more then one page, then you can use the automatic Jekyll support (static site CMS using Markdown).

Switching back and forth will just be a DNS change (at least with the current static 1-page HTML).

**Comment by kenbowen** [comment]
Exists as alsprolog.com
