### ISSUE TITLE
Incorrect behavior for some Break Handler options

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#37]
The following problems with the Break Handler package occur in both alspro and alsdev.

Create a file t.pro containing f :- write(foo), f.  [Or just assert that clause].
Execute:  alspro t.pro
Run: ?-f.     Immediately hit ^C to interrupt the spew.
You get the break handler:

    Break Handler
    ------------------------
    a - Abort Computation *
    b - Break shell
    c - Continue
    d - Debug
    e - Exit Prolog
    f - Fail
    p - Return to Previous Break Level
    s - Show goal broken at
    t - Stack trace
    ? - This message
Break(1) >

Items a-e, p work correctly.  Option f will work correctly for this case [f :- write(foo), f.], but below we show a different case in which it fails.

Options s,t fail, showing bits of the underlying interrupt handler code (typically different bits each time this is carried out):
Choice s:
========
Break(1) >s
Break at: sio:_A is 866-0
    Break Handler
    ------------------------
    a - Abort Computation *
    b - Break shell
    c - Continue
    d - Debug
    e - Exit Prolog
    f - Fail
    p - Return to Previous Break Level
    s - Show goal broken at
    t - Stack trace
    ? - This message
Break(1) > 

Choice t:
=========
Break(1) >t
(1) builtins:stack_trace(1)
(2) builtins:
    break_handler(stack_trace,sio,'$is_delay_var'(zipper),
        als_shl_mgr(als_shl_mgr,builtins,1...))
(3) builtins:catch0(builtins,?,?)
(4) builtins:breakhandler(sio,'$is_delay_var'(zipper))
(5) sio:wd(zipper,1200,400,nospace,nospace,[_A|_B],_B...)
(6) sio:wd(zipper,400,?,[],?)
(7) sio:
    write_term0(
        stream_descriptor('',open,console,'standard output',[noinput,...],
            false...),
        zipper,winfo(false,false,false,true...))
(8) user:f
    Break Handler
    ------------------------

To demonstrate option f failing, create a file t2.pro containing the following:
a :- b.
b :- c.
c :- d.
Execute alspro t2.pro
Run (and interrupt with control-C) at the indicated point, getting the printed result:
?- trace a.
(1) 1 call: user:a?
(2) 2 call: user:b?^C
    Break Handler
    ------------------------
    a - Abort Computation *
    b - Break shell
    c - Continue
    d - Debug
    e - Exit Prolog
    f - Fail
    p - Return to Previous Break Level
    s - Show goal broken at
    t - Stack trace
    ? - This message
Break(1) >f
Error: System error: sio:get_line0(debugger_input,_A,_B)
- Goal:          sio:get_line0(debugger_input,_A,_B)
- errno:         0
- Throw pattern: error(system_error,
                     [sio:get_line0(debugger_input,_A,_B),errno(0)])

**Comment by chuckhoupt** [comment]
Maybe this bug should be split in three, one each for `s - Show goal`, `t - Stack Trace` and `f - Fail`?

Also, the bugs should explicitly say what is the expected correct result. In particular, what is the expected output from `s`? I agree that `sio:_A is 866-0` is a bit inscrutable, but what should it be? `sio:$is_delay_var`, `sio:write_term0` or something else?

About `f`, is the behavior a bug? If you interrupt `trace/1` (i.e. you are debugging `builtins:trace/1`), and then fail its attempt to read a trace-command, then it seems reasonable for `trace/1` to throw an exception.

**Comment by kenbowen** [comment]
I think all 3 of them come down to what the expectations of t/s/f are (as a group): either a relatively a) "pretty display of the user's program execution" or b) an "all the sausage" display of everything entering into the computation in ALS Prolog.  If b), then there is nothing to be done, and this is not a bug/issue, and should be closed, and perhaps an enhancement to create a "pretty execution view" should be posted.   I'm now inclined towards this view.

**Comment by kenbowen** [comment]
Replaced by #42.  Existing behavior of t/s/f is not buggy, just ugly.
