### ISSUE TITLE
alsdev: Debugger/Spy Panel: Console coordination

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#45]
Prolog > Consult:  load queens.pro
Tools > Debugger
    Click on Debugger console
    Tools > Spy
    Switch Modules to user (should be default)
    In Prolog Env console, type spy all_queens.

Result:  Console shows yes. , but no change to Spying On column of Spy panel.
    Click Refresh Preds in Spy panel;
Result:  all_queens/0 now shows in Spying On column.
Desirable enhancement:  
    all_queens/0 should show in Spying On column without need to click Refresh Preds.

**Comment by chuckhoupt** [comment]
Stepping back: what's the scope of this enhancement? Currently it only requests auto-refresh for spy, but the pull request #48 adds auto-refresh for spy and consult, but ignores nospy, assert, retract, etc?

It feels like the true desired enhancement is for a fully automated refresh of the Spy Panel, which could be described as:

*Spy Panel Auto-Refresh Enhancement:*
- Remove Refresh buttons
- Implement (efficient) auto-Refresh of pred/mod/spy lists.

One idea for implementing this is to add an efficient idle-time refresh in the GUI, so no modification would be needed to spy/nospy/assert/retract/consult/etc.

**Comment by kenbowen** [comment]
Ah, thanks for the nospy reminder.  I was focused on forward motion: adding a spy, doing a consult.  

The enhancement grew as I worked on it.  But it was basically about co-ordinating the Spy panel with old-fashioned actions in the console (old Prolog programmers who remember how to type spy….  :-).

Spy and consult are already dealt with;  nospy will take a couple of insertions of the “refresh” line too.  So idle-time refresh strikes me as a little heavy duty (both code and processing) just to achieve that coordination.  

Assert/retract don’t directly interact with spying except for edge cases.  They dynamically modify a running program, but they don’t change whether or not something in the program gets spied on.  Obviously, asserting/retracting could change what shows in the Predicates column, but since what I was after was coordination of the Spy panel with things typed in the console, I’m inclined to think of assert/retract typed in the console as an edge case.  I guess it would be an argument for not removing the Refresh buttons.  However, only one is needed, since the main machinery refreshes the whole panel all at once.  So one could be dropped, and the remaining one just be Refresh (not so ugly).

**Comment by kenbowen** [comment]
Fixed by https://github.com/AppliedLogicSystems/ALSProlog/commit/0c344319a105a55f506c86b3ce49384c792d3963
