### ISSUE TITLE
Add -h/--help flag to alspro

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#49]
It might also be nice to add a -h or --help option to alspro, which could give a terse description of alspro ~~arguments~~ options and also point to docs elsewhere.

**Comment by kenbowen** [comment]
I assume alspro arguments = (very) terse versions of Wiki 13.2 + 13.4 + 13.5 + 13.6 + 13.7.
Should the 13.7 segment mention all the switches, or just a subset, for instance

	—s [mentioned in 13.2-13.4, so maybe not much here]  -g   -q/-v  -w  -p

with very brief listing of all the others together with docs pointer(s) for them?

Note wrt: -w:  I think we are currently defaulting to giving the non-existent error message.  Maybe we should flipflop that.

**Comment by chuckhoupt** [comment]
The "arguments" terminology wasn't right. I meant options (also sometimes called switches or flags). Typically, -h help is just a brief usage line, a list of 1-line option descriptions, and sometimes a see-more reference. So mostly [13.7](/AppliedLogicSystems/ALSProlog/wiki/13-Using-the-Prolog-Shell#137-als-prolog-command-line-options). Some examples from Ruby, and Perl:

```
$ ruby -h
Usage: ruby [switches] [--] [programfile] [arguments]
  -0[octal]       specify record separator (\0, if no argument)
  -a              autosplit mode with -n or -p (splits $_ into $F)
  -c              check syntax only
  -Cdirectory     cd to directory before executing your script
  -d              set debugging flags (set $DEBUG to true)
...
```

```
$ perl -h
Usage: perl [switches] [--] [programfile] [arguments]
  -v                print version, patchlevel and license
...  
Run 'perldoc perl' for more help with Perl.
```

**Comment by chuckhoupt** [comment]
> Note wrt: -w: I think we are currently defaulting to giving the non-existent error message. Maybe we should flipflop that.

The -w option doesn't seem to be exist -- probably obsoleted by `dynamic/1` declarations. I've removed from Wiki.
