### ISSUE TITLE
alsdev: Prolog > Set Directory fails

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#6]
Throws Application Error window - Error: invalid command name "getDirectory"
Details:
invalid command name "getDirectory"
invalid command name "getDirectory"
    while executing
"getDirectory"
    (procedure "set_directory" line 3)
    invoked from within
"set_directory"
    ("uplevel" body line 1)
    invoked from within
"uplevel $a"

**Comment by chuckhoupt** [comment]
Ah yea. getDirectory is an extra Tcl/Tk extension/plugin. The code for getDirectory is in the tree, but isn't part of the build process -- don't know if it would compile, or if Tk has something better these days.

**Comment by kenbowen** [comment]
Note:  On win32, no error is thrown, just nothing happens.

**Comment by kenbowen** [comment]
Fixed by https://github.com/AppliedLogicSystems/ALSProlog/commit/5a599d1a2ad4d86b3c0aaf07ce86ac3a0dbfe7bf
Calls to getDirectory replaced by tk_chooseDirectory
