### ISSUE TITLE
Help option cause alspro to exit with error status

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#72]
Steps & Result:
```
$ alspro --help
.....
$ echo $?
2
```

Expected Result: exit status should be 0 for success.

**Comment by kenbowen** [comment]
Problem doesn't even require the --help switch:
KB-SSD > ./alspro
ALS Prolog (Threaded) Version 3.2.0-11-g2c53e81 [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.
?- halt.
KB-SSD > echo $?
2

**Comment by chuckhoupt** [comment]
Hmm, `exit` returns 0 (as does closing shell input via Ctrl-D). I wonder why there is a difference with halt.

**Comment by kenbowen** [comment]
Rather mysterious.
halt is pbi_halt, which calls als_exit(status) from main.c
I encumbered als_exit with some print routines:

void
als_exit(status)
    int   status;
{
PI_oprintf("\nENTER als_exit status=%d\n", status);
    exit_status = status;
PI_oprintf("\nENTER als_exit exit_status=%d\n", exit_status);

    longjmp(exit_return, 1);
}

Here’s running it:

KB-SSD > ./alspro
ALS Prolog (Threaded) Version 3.2.0-11-g2c53e81-dirty [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.

?- halt.

ENTER pbi_halt

ENTER als_exit status=0

ENTER als_exit exit_status=0

KB-SSD > echo $?
2
KB-SSD >

At lines 115-116 in main.c we have:
static int exit_status = 0;
static jmp_buf exit_return;

**Comment by kenbowen** [comment]
In blt_shl.pro:

continue_prolog_loop(halt)
        :-!,
        halt.
continue_prolog_loop(exit)
        :-!,
        fail.
continue_prolog_loop(end_of_file)
        :-!,
        fail.
continue_prolog_loop(Status).

If the �halt� in the first clause is changed to fail, we get the desired behavior:

continue_prolog_loop(halt)
        :-!,
%        halt.
        fail.

ALS Prolog (Threaded) Version 3.2.0-11-g2c53e81-dirty [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.

?- halt.
KB-SSD > echo $?
0

Don�t know what halt was supposed to do that was different (see my previous email).
��Ken

**Comment by kenbowen** [comment]
A bit more mystery:  The problem doesn�t occur with alsdev:

KB-SSD > ./alsdev
	<< Issue halt in the alsdev console >>
KB-SSD > echo $?
0

From blt_dvsh.pro:

continue_prolog_loop(halt)
        :-!,
        halt.
continue_prolog_loop(exit)
        :-!,
        fail.
continue_prolog_loop(Status).

Very strange.
�Ken
