### ISSUE TITLE
Multi-line console input fails

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#75]
KB-SSD > ./alspro
ALS Prolog (Threaded) Version 3.2.0-14-g6bf3764-dirty [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.

?- abc
?-_def.

def.
^Syntax error 
	'standard input', line 2: Fullstop (period) expected

?-

**Comment by chuckhoupt** [comment]
What's the expected result? Maybe the syntax error should reference line 1?

**Comment by kenbowen** [comment]
Unless I’m confused, it should try to assemble a readable term off multiple lines; so it should have read 
	abcdef
then tried to execute it, and then either said 

Error: Operation attempted on object of type procedure which does not exist

or said
no.

And
?- tr
?-_ue.

should read true 

and say 
yes.

**Comment by chuckhoupt** [comment]
But wouldn't a newline be treated the same as other whitespace? For example, a space produces the following error:
```
?- abc def.

abc def.
    ^Syntax error 
	'standard input', line 3: Fullstop (period) expected
```

**Comment by kenbowen** [comment]
But then why do we have the secondary prompt:

?-_

IIRC, the point was that if a period had not been encountered at the end of a line, then the newline at the end of an incomplete line was discarded, and we went on accumulating the term.

—Ken

**Comment by chuckhoupt** [comment]
I think the secondary prompt allows one to enter multi-line statements, like:
```
?- X=1,
?-_Y=2.

X=1 
Y=2 

yes.
```

**Comment by kenbowen** [comment]
Ok, I can go with that.  I’ll shut down this issue.
