### ISSUE TITLE
Linenoise input causes debugger trace to double the '?' in prompts

### ISSUE THREAD

**Issue by kenbowen** [AppliedLogicSystems/ALSProlog#79]
As in:

?- trace r.
(1) 1 call: user:r??-

**Comment by chuckhoupt** [comment]
I see something like the undefined unicode character replacement glyph (�). Possibly `console_prompt` is not initialize, so random memory is displayed.

**Comment by kenbowen** [comment]
It’s slippery.  Note, my replacement glyph (�) shows as a square box around the ?.
Occasionally, after starting alspro, the trace shows the replacement glyph instantiated to “?-“, but mostly not.
Here’s what I know so far:

A.  The central procedure is at about 1825 in builtins/debugger.pro:

getresponse_cont(Port,Box,Depth,Module,Goal,Resps,Response)
        :-
       put_code(debugger_output,0'\?),
       flush_output(debugger_output),
       get_atomic_nonblank_char(debugger_input, R),
       dmember(R-Resp0,Resps),
       !,
       disp_getresponse_cont(Resp0, Port,Box,Depth,Module,Goal,Resps,Response).

The code
  put_code(debugger_output,0'\?),
  flush_output(debugger_output),

outputs the initial ? in 
	(1) 1 call: user:a?׻׻�
which I verified by changing the 0'\? to 0’\@ and got
	(1) 1 call: user:a@׻�

B. I don’t think ‘console_prompt’ and linenoise are directly involved.  In bsio.c,
at line 283, I changed 
	const char *console_prompt;
to
	const char *console_prompt="#”;

and at line 355, I changed

    if (console_prompt == NULL){
        console_prompt = "?- ";
    }
to 
    if (console_prompt == NULL){
        console_prompt = "#@#?- ";
    }

But none of these # chars show up in a debugger trace.

C. [Returning to A] Drilling down thru
	 get_atomic_nonblank_char(debugger_input, R)
leads to [builtins/sio.pro] the call:

	sio_readln(Stream,Line,EndFlag),     [about line 3882]

which is defined in generic/bsio.c at line 6498

If the ׻ char is emitted here, I don’t see it (yet).

Cheers,
——Ken

**Comment by chuckhoupt** [comment]
Another related issue is that if you do line-editing within the debugger, the prompt gets lost. To implement this, the full prompt must be set. For example, for `trace true.`, then first prompt would be `(1) 1 call: user:true?`

**Comment by kenbowen** [comment]
> On Sep 14, 2016, at 5:23 PM, Chuck Houpt <notifications@github.com> wrote:
> 
> Another related issue is that if you do line-editing within the debugger, the prompt gets lost.

Not sure what you mean here.  Do you mean giving a “b” response to go into a break, which then acts like a normal command line (and does permit editing)?  {Note: after attempting to exit from such a break, there’s a bug.}

> To implement this, the full prompt must be set. For example, for trace true., then first prompt would be (1) 1 call: user:true?
Right, and now you’re to give one of the debug responses
    a - Abort computation
    b - Break to Prolog shell
    c - Creep to next port
    d - Set print depth
    e - Exit Prolog
    f - Fail goal
    i - Info: Print system statistics
    j - Jump to next spy point or current port of call
    l - Leap to next spy point
    m - Change print mode
    n - Continue execution with tracing off
    N - Turn off trace (in break)
    r - Retry goal
    s - Skip to next port of call
    t - Print stack Trace
    ? - ?
——Ken

**Comment by kenbowen** [comment]
I tried to pin the output of � below:

debugger.pro
====
getresponse_cont(Port,Box,Depth,Module,Goal,Resps,Response)
        :-
        put_code(debugger_output,0'\?),
        flush_output(debugger_output),
        get_atomic_nonblank_char(debugger_input, R),
===============================
sio.pro
=====
get_atomic_nonblank_char(Stream,Char)
        :-
        get_line(Stream, Line),

get_line(Stream,Line) :-
        get_line0(Stream,Line0,EndFlag),

get_line0(Stream,Line,EndFlag) :-
					<<<<< [test] write(debugger_output, '++'),
        sio_readln(Stream,Line,EndFlag),
        !.
===============================
bsio.c:
=====
int
sio_readln()
{
    PWord v1, v2, v3, vBuf;
    int   t1, t2, t3, tBuf;
    UCHAR *buf;
    int   cpos, lpos, wpos;
    int   eoln_read, read_length, nl;

					<<<<<<<<[test] printf("||");

    w_get_An(&v1, &t1, 1);
    w_get_An(&v2, &t2, 2);
    w_get_An(&v3, &t3, 3);
===============================
zz.pro:
a :- b.
b :- c.
c :- d.
d.
===============================
Output:
=====
KB-SSD > ./alspro zz.pro
ALS Prolog (Threaded) Version 3.2.0-38-g439e823-dirty [darwin]
   Copyright (c) 1987-2015 Applied Logic Systems, Inc.

Attempting to consult zz.pro...
... consulted /Users/ken/ALS/GitHub/ALSProlog/core/unix/darwin/zz.pro
?- trace a.
(1) 1 call: user:a?++׻�||||
++(2) 2 call: user:b?++�׻||||||||
++(3) 3 call: user:c?++׻�||||||||
++(4) 4 call: user:d?++׻�||||||||
++(4) 4 exit: user:d?++�׻||||||||
++(3) 3 exit: user:c?++׻�||||||||
++(2) 2 exit: user:b?++׻�||||||||
++(1) 1 exit: user:a?++׻�||||||||

yes.
?- 

I presume that one can’t necessarily trust the order of everything written to debugger_output, given that one is trying to read debugger_input, but this is suggestive.
Now, when I do the trace a 2nd time (still in the same alspro instance), the uninstantiated glyph is replaced by the standard prompt “?- “ (below), but that’s not right of course.  But where could it be coming from????

?- trace a.||||
++(1) 1 call: user:a?++?- ||||
++(2) 2 call: user:b?++?- ||||||||
++(3) 3 call: user:c?++?- ||||||||
++(4) 4 call: user:d?++?- ||||||||
++(4) 4 exit: user:d?++?- ||||||||
++(3) 3 exit: user:c?++?- ||||||||
++(2) 2 exit: user:b?++?- ||||||||
++(1) 1 exit: user:a?++?- ||||||||

yes.
?- 

I went back to line 283 of bsio.c and set
	const char *console_prompt="%%$";
but none of that shows when I repeat the 2 traces above.

——Ken

**Comment by kenbowen** [comment]
What I thought was a bug on exiting from a break in a debugger trace is really the uninstantiated variable/glyph getting instantiated to ‘Break (1) ‘  as seen here:


?- trace a.
(1) 1 call: user:a?׻�       <return>
(2) 2 call: user:b?׻�       <return>
(3) 3 call: user:c?׻�b
Break (1) ?- true.          <return>

yes.                        <return>
Break (1) ?-                <^D>
(3) 3 call: user:c?Break (1) ?- 
(4) 4 call: user:d?Break (1) ?- 

Haven’t got a handle yet on where ‘Break (1) ‘ is output.
—Ken
