### ISSUE TITLE
More dependencies for compiling in CentOS 

### ISSUE THREAD

**Issue by dram** [AppliedLogicSystems/ALSProlog#84]
When trying to compile ALSProlog in CentOS 7, I found that besides packages already listed in README, following packages are also needed:

```
libgcc.i686 tcl.i686 tk.i686 tcl-devel.i686
```

**Comment by kenbowen** [comment]
I believe the README covers these with the “Generally statement”, doesn’t it?

    Generally, a GNU/Linux OS with standard build tools (Make, GCC with 32-bit support), Git, and Tcl/Tk.

Isn’t the intent of the individual OS entries to point to some items that aren’t necessarily included by the “Generally statement”?  

From README.md:

Build Dependencies
------------------

### Linux

Generally, a GNU/Linux OS with standard build tools (Make, GCC with 32-bit support), Git, and Tcl/Tk. Packages for popular distributions:
……
CentOS/Fedora: `sudo yum groupinstall 'Development Tools' && sudo yum install glibc-devel.i686 tk-devel.i686 git`
….

**Comment by chuckhoupt** [comment]
Hi @dram, thanks for the feedback. I'll test it out on CentOS 7 again. Possibly I didn't run a full test with 64-bit CentOS 7, so I missed some packages.

**Comment by dram** [comment]
@kenbowen, I think that “Generally statement” is for distros other then Debian/Ubuntu and CentOS/Fedora.

@chuckhoupt, sorry, I forgot to mention arch info. Here's the details:

```
% cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
~
% uname -m
x86_64
```
