### ISSUE TITLE
Semi-duplicate set of ALS examples in alsp_src/test. Delete?

### ISSUE THREAD

**Issue by chuckhoupt** [AppliedLogicSystems/ALSProlog#9]
There's an old version of the ALS examples in `core/alsp_src/test/als_exmp/` I would have just deleted it, but there are some extra files (`animals.pro, count.pro`), and a fair number of differences. 

@kenbowen can you review the diffs, and determine if anything needs saving, or if it can all be deleted?

Here's the command I used at the top of the tree to view the diffs:

`diff -wB -ruN  core/alsp_src/tests/als_exmp/ examples/als/ | less`

**Comment by kenbowen** [comment]
I haven�t dug in on the individual differences yet, but here�s the top level status:

autotest looks for files in:
	core/alsp_src/tests/als_exmp   [change this to examples/als]
	core/alsp_src/tests/tsuite

The files autotest looks for are listed in atest_db.pro
	Group: Standard ALS examples:
	    bench, jobs, nrev, queens

	Group: suite  � everything else in atest_db.pro

In als_exmp but not listed in atest_db:
	A) Also in examples/als:
		dc, diff, hickory, id, mission, nim

	B) Not in examples/als:		[move to examples/als]
		animals, count

I�ll consolidate core/alsp_src/tests/als_exmp into examples/als, moving animals & count, and merging any significant differences after I examine the detailed individual diffs.

�Ken

**Comment by kenbowen** [comment]
Closed by commits:
ec9e4cced32d68e4d283588b5f372fa51bdf7b12
c8c35f616e780a42351017760c47b57bed53dce7
